### ISSUE TITLE
pip install -r requirements.txt error

### ISSUE THREAD

**Issue by FrugalGuy** [naschorr/electronic-component-label-builder#1]
```   $ pip install -r requirements.txt
Collecting click==6.2
  Downloading click-6.2-py2.py3-none-any.whl (70 kB)
Collecting inflect==0.2.5
  Downloading inflect-0.2.5-py2.py3-none-any.whl (58 kB)
Collecting Pillow==3.0.0
  Downloading Pillow-3.0.0.zip (9.9 MB)
Using legacy 'setup.py install' for Pillow, since package 'wheel' is not installed.
Installing collected packages: Pillow, inflect, click
    Running setup.py install for Pillow: started
    Running setup.py install for Pillow: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'c:\tools\python385\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RonCraig\\AppData\\Local\\Temp\\pip-install-sz65qyur\\pillow_b62d326a9ef147a3baadf35895dd40fc\\setup.py'"'"'; __file__='"'"'C:\\Users\\RonCraig\\AppData\\Local\\Temp\\pip-install-sz65qyur\\pillow_b62d326a9ef147a3baadf35895dd40fc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\RonCraig\AppData\Local\Temp\pip-record-exeqty6d\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\tools\python385\Include\Pillow'
         cwd: C:\Users\RonCraig\AppData\Local\Temp\pip-install-sz65qyur\pillow_b62d326a9ef147a3baadf35895dd40fc\
    Complete output (133 lines):
    Single threaded build for windows
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\PIL
    copying PIL\BdfFontFile.py -> build\lib.win32-3.8\PIL
    copying PIL\BmpImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\BufrStubImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\ContainerIO.py -> build\lib.win32-3.8\PIL
    copying PIL\CurImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\DcxImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\EpsImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\ExifTags.py -> build\lib.win32-3.8\PIL
    copying PIL\features.py -> build\lib.win32-3.8\PIL
    copying PIL\FitsStubImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\FliImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\FontFile.py -> build\lib.win32-3.8\PIL
    copying PIL\FpxImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\GbrImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\GdImageFile.py -> build\lib.win32-3.8\PIL
    copying PIL\GifImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\GimpGradientFile.py -> build\lib.win32-3.8\PIL
    copying PIL\GimpPaletteFile.py -> build\lib.win32-3.8\PIL
    copying PIL\GribStubImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\Hdf5StubImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\IcnsImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\IcoImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\Image.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageChops.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageCms.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageColor.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageDraw.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageDraw2.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageEnhance.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageFile.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageFilter.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageFont.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageGrab.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageMath.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageMode.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageMorph.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageOps.py -> build\lib.win32-3.8\PIL
    copying PIL\ImagePalette.py -> build\lib.win32-3.8\PIL
    copying PIL\ImagePath.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageQt.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageSequence.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageShow.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageStat.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageTk.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageTransform.py -> build\lib.win32-3.8\PIL
    copying PIL\ImageWin.py -> build\lib.win32-3.8\PIL
    copying PIL\ImImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\ImtImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\IptcImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\Jpeg2KImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\JpegImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\JpegPresets.py -> build\lib.win32-3.8\PIL
    copying PIL\McIdasImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\MicImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\MpegImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\MpoImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\MspImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\OleFileIO.py -> build\lib.win32-3.8\PIL
    copying PIL\PaletteFile.py -> build\lib.win32-3.8\PIL
    copying PIL\PalmImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\PcdImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\PcfFontFile.py -> build\lib.win32-3.8\PIL
    copying PIL\PcxImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\PdfImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\PixarImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\PngImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\PpmImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\PsdImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\PSDraw.py -> build\lib.win32-3.8\PIL
    copying PIL\PyAccess.py -> build\lib.win32-3.8\PIL
    copying PIL\SgiImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\SpiderImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\SunImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\TarIO.py -> build\lib.win32-3.8\PIL
    copying PIL\TgaImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\TiffImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\TiffTags.py -> build\lib.win32-3.8\PIL
    copying PIL\WalImageFile.py -> build\lib.win32-3.8\PIL
    copying PIL\WebPImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\WmfImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\XbmImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\XpmImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\XVThumbImagePlugin.py -> build\lib.win32-3.8\PIL
    copying PIL\_binary.py -> build\lib.win32-3.8\PIL
    copying PIL\_util.py -> build\lib.win32-3.8\PIL
    copying PIL\__init__.py -> build\lib.win32-3.8\PIL
    running egg_info
    writing Pillow.egg-info\PKG-INFO
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    writing top-level names to Pillow.egg-info\top_level.txt
    reading manifest file 'Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'Pillow.egg-info\SOURCES.txt'
    copying PIL\OleFileIO-README.md -> build\lib.win32-3.8\PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\RonCraig\AppData\Local\Temp\pip-install-sz65qyur\pillow_b62d326a9ef147a3baadf35895dd40fc\setup.py", line 733, in <module>
        setup(
      File "c:\tools\python385\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "c:\tools\python385\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\tools\python385\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\tools\python385\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\tools\python385\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\tools\python385\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\tools\python385\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\tools\python385\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\tools\python385\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\tools\python385\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\tools\python385\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\tools\python385\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\RonCraig\AppData\Local\Temp\pip-install-sz65qyur\pillow_b62d326a9ef147a3baadf35895dd40fc\setup.py", line 513, in build_extensions
        raise ValueError(
    ValueError: --enable-jpeg requested but jpeg not found, aborting.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\tools\python385\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RonCraig\\AppData\\Local\\Temp\\pip-install-sz65qyur\\pillow_b62d326a9ef147a3baadf35895dd40fc\\setup.py'"'"'; __file__='"'"'C:\\Users\\RonCraig\\AppData\\Local\\Temp\\pip-install-sz65qyur\\pillow_b62d326a9ef147a3baadf35895dd40fc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\RonCraig\AppData\Local\Temp\pip-record-exeqty6d\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\tools\python385\Include\Pillow' Check the logs for full command output.

```

**Comment by FrugalGuy** [comment]
I overcame the error by ignoring it. :-)
I manually installed click, then inflect, then pillow. Once I did that, the program worked.

```
$ python eclb.py
Traceback (most recent call last):
  File "eclb.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'

AzureAD+RonCraig@almond MINGW64 /c/Users/IBM_ADMIN/Documents/githubs/electronic-component-label-builder (master)
$ pip install click
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Installing collected packages: click
Successfully installed click-7.1.2

AzureAD+RonCraig@almond MINGW64 /c/Users/IBM_ADMIN/Documents/githubs/electronic-component-label-builder (master)
$ python eclb.py
C:\Users\IBM_ADMIN\Documents\githubs\electronic-component-label-builder\helpers.py:46: SyntaxWarning: "is" with a literal. Did you
 mean "=="?
  if(argLen is 0):
C:\Users\IBM_ADMIN\Documents\githubs\electronic-component-label-builder\helpers.py:48: SyntaxWarning: "is" with a literal. Did you
 mean "=="?
  elif(argLen is 1):
C:\Users\IBM_ADMIN\Documents\githubs\electronic-component-label-builder\helpers.py:50: SyntaxWarning: "is" with a literal. Did you
 mean "=="?
  elif(argLen is 2):
C:\Users\IBM_ADMIN\Documents\githubs\electronic-component-label-builder\componentBuilder.py:282: SyntaxWarning: "is" with a litera
l. Did you mean "=="?
  if(thisChar is '.' or (thisChar is '0' and digitCounter is 0)):
C:\Users\IBM_ADMIN\Documents\githubs\electronic-component-label-builder\componentBuilder.py:282: SyntaxWarning: "is" with a litera
l. Did you mean "=="?
  if(thisChar is '.' or (thisChar is '0' and digitCounter is 0)):
C:\Users\IBM_ADMIN\Documents\githubs\electronic-component-label-builder\componentBuilder.py:282: SyntaxWarning: "is" with a litera
l. Did you mean "=="?
  if(thisChar is '.' or (thisChar is '0' and digitCounter is 0)):
Traceback (most recent call last):
  File "eclb.py", line 5, in <module>
    import componentBuilder
  File "C:\Users\IBM_ADMIN\Documents\githubs\electronic-component-label-builder\componentBuilder.py", line 1, in <module>
    import inflect
ModuleNotFoundError: No module named 'inflect'

AzureAD+RonCraig@almond MINGW64 /c/Users/IBM_ADMIN/Documents/githubs/electronic-component-label-builder (master)
$ pip install inflect
Collecting inflect
  Downloading inflect-5.0.2-py3-none-any.whl (31 kB)
Installing collected packages: inflect
Successfully installed inflect-5.0.2

AzureAD+RonCraig@almond MINGW64 /c/Users/IBM_ADMIN/Documents/githubs/electronic-component-label-builder (master)
$ python eclb.py
Traceback (most recent call last):
  File "eclb.py", line 7, in <module>
    import sheetBuilder
  File "C:\Users\IBM_ADMIN\Documents\githubs\electronic-component-label-builder\sheetBuilder.py", line 2, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'

AzureAD+RonCraig@almond MINGW64 /c/Users/IBM_ADMIN/Documents/githubs/electronic-component-label-builder (master)
$ pip install Pillow
Collecting Pillow
  Downloading Pillow-8.1.0-cp38-cp38-win32.whl (1.9 MB)
Installing collected packages: Pillow
Successfully installed Pillow-8.1.0

AzureAD+RonCraig@almond MINGW64 /c/Users/IBM_ADMIN/Documents/githubs/electronic-component-label-builder (master)
$ python eclb.py
Usage: eclb.py [OPTIONS] PATH_TO_COMPONENT_DATA
Try 'eclb.py --help' for help.

Error: Missing argument 'PATH_TO_COMPONENT_DATA'.

```
